export const POSITIONS = {
  GK: "Goalkeeper",
  DR: "Right Wing Back",
  FB: "Fullback",
  DC: "Central Defense",
  DCL: "Central Defense",
  DCR: "Right Central Defense",
  DL: "Left Wing Back",
  SW: "Sweeper",
  RM: "Right Midfielder",
  DM: "Defensive Midfielder",
  DML: "Left Defensive Midfielder",
  DMR: "Defensive Midfielder",
  MC: "Central Midfielder",
  MCL: "Left Central Midfielder",
  MCR: "Right Central Midfielder",
  AM: "Attacking Midfielder",
  AML: "Left Attacking Midfielder",
  AMR: "Right Attacking Midfielder",
  LM: "Left Midfielder",
  RW: "Right Winger",
  ST: "Striker",
  FWL: "Left Forwarder",
  FWR: "Right Forwarder",
  LW: "Left Winger"
};
